on:
  workflow_call:
  
name: global workflow for caisy

jobs:
  google:
    uses: caisy-io/github-workflows/.github/workflows/google_dev.yml@main
  azure:
    uses: caisy-io/github-workflows/.github/workflows/azure_dev.yml@main
